---
title: 'Primer of Ecology with $\textsf{R}$: chapter 5'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    toc: false
    code_folding: hide
    number_sections: false
    theme: cerulean
    highlight: haddock
  pdf_document:
    toc: false
---

``` {r setup, echo = TRUE, message = FALSE, warning = FALSE}

knitr::opts_chunk$set(fig.width = 6, fig.height = 4, # fig.path = 'Figs/',
                      echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(RColorBrewer)

### The book has an R package! 
library(primer) # install.packages('primer')

```

# Chapter 5: Lotka–Volterra Interspecific Competition {.tabset}

## 5.1. Basics

Let $\alpha_{11} = \alpha_{22} = 0.1, \alpha_{12} = 0.05, \alpha_{21} = 0.01$.

(a) Determine $N_1^∗, N_2^∗, K_1, K_2$.
(b) Draw (by hand, or in R) the ZNGIs (zero net growth isoclines); include arrows that indicate trajectories, and label the axes.
(c) Select other values for the $\alpha$ and repeat (a) and (b); swap your answers with a friend, and check each other’s work.
(d) Start with equilibria for competing species, and show algebraically that when interspecific competition is nonexistent, species reach their carrying capacities.

## 5.2. Derive and simplify...

...the expression for $N_1^∗/N_2^∗$ in terms of the $\alpha$.

## 5.3. Show the derivations...

...of the partial derivatives of $dN_2/dt$, with respect to $N_2$ and to $N_1$; begin with eq. 5.6.

## 5.4. Total community size

Assume for convenience that $\alpha_{11} = \alpha_{22}$ and $\alpha_{12} = \alpha_{21}$, and let $N_T = N_1 + N_2$. (a) Write $N_T^∗$ as a function of $\alpha_{11}, \alpha_{22}, \alpha_{12}, \alpha_{21}$.
(b) Describe in words how $N_T$ varies as $\alpha_{ij}$ varies from $\alpha_{ii} \rightarrow 0$.
(c) Graph (by hand, or in R) the relation between $N_T$ versus $\alpha_{ij}$. Let $\alpha_{ii} = 0.01$.

## 5.5. Interpret the Routh-Hurwitz criterion...

...in terms of species relative inter- and intraspecific competitive abilities.

## 5.6. The Jacobian matrix

Here we turn words into math. Note that this is one way of making our as- sumptions very precise and clear. In each case below (a.–d.), (i) use algebraic inequalities between the $\beta$s and between the $\alpha$s to show what the assumptions imply for the equalities and inequalities with respect to all $\alpha$s, (ii) use these inequalities to simplify the Jacobian matrix (eq. (5.21) as much as possible, (iii) show algebraically how these (in)equalities determine the sign of each element of the Jacobian, and (iv) explain in words how the magnitudes of the Jacobian elements determine stability properties.

(a) Assume that both species are functionally equivalent, and intraspecific competition is more intense than interspecific competition.
(b) Assume species are functionally equivalent and that each species has a greater impact on each other than they do on themselves.
(c) Assume species are functionally equivalent and interspecific competition is
precisely equal to intraspecific competition.
(d) Assume species have the same carrying capacity, and can coexist, but that species 1 is dominant.
(e) Assume species 1 is the better competitor (note: this may have multiple interpretations).
(f) Assume species 1 and 2 are equivalent (note: this may have multiple interpretations).